name: shapelets
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numba
  - numpy
  - scipy
  - faiss
  - scikit-learn
  - pyts
  - matplotlib
  - seaborn
  - streamlit
  - jupyterlab
  - peewee
  - psycopg2

